### PR TITLE
Add SlideShow to HomePage

### LINKED ISSUE #30: Change home page behavior
The home page is currently useless after sign in. So make the home page to be the generate page.
Alternativly, add so other functionallity to the home page.

### PR DESCRIPTION
**Pull request by Danielsio**
## Description

Added SlideShow component to the homepage
The component contains effects from 3rd party react library 

## Relevent issues:
close #30

### CODE REVIEW

**Comment by Danielsio** [comment]
Hey Team, let me know if you think something is missing, or can I do something extra to make this PR Merge-Ready ASAP.

**Comment by oshriFadlon1** [comment]
I opened the site in the preview and I don't see the arrows on the pictures

**Comment by Danielsio** [comment]
> I opened the site in the preview and I don't see the arrows on the pictures

Can you please spot on the code what needs to be changed to fix this problem ?

**Comment by itayf9** [comment]
> Hey Team, let me know if you think something is missing, or can I do something extra to make this PR Merge-Ready ASAP.

Well, I still think there are UI improvements need to be done before merging (not your fault, probably the 3rd party package's fault).
First, the text of "Before" and "After" is not looking so good. 
Second, that green border (can live with it but prefer to remove it).
Third, no arrows are shown to move between the images, but there are such buttons in the edges of the images.

Anyway, I've found a nice 3rd party that may be better (I haven't tried it yet), called "React SlideShow". 
[https://react-slideshow-image.netlify.app/?path=/docs/examples-fade--default](https://react-slideshow-image.netlify.app/?path=/docs/examples-fade--default)

**Comment by Danielsio** [comment]
> > Hey Team, let me know if you think something is missing, or can I do something extra to make this PR Merge-Ready ASAP.
> 
> Well, I still think there are UI improvements need to be done before merging (not your fault, probably the 3rd party package's fault). First, the text of "Before" and "After" is not looking so good. Second, that green border (can live with it but prefer to remove it). Third, no arrows are shown to move between the images, but there are such buttons in the edges of the images.
> 
> Anyway, I've found a nice 3rd party that may be better (I haven't tried it yet), called "React SlideShow". https://react-slideshow-image.netlify.app/?path=/docs/examples-fade--default

**Comment by oshriFadlon1** [comment]
the picture not site good in the frame they have.
It cut half of the last day in the picture.

**Comment by Danielsio** [comment]
> the picture not site good in the frame they have. It cut half of the last day in the picture.

yea, it did

**Review by itayf9 — COMMENTED** [review]
I've remove the green border from the images.
Still need to scale the images so they won't be cropped.

**Comment by oshriFadlon1** [comment]
The pictures are not sharp
You can't see what is written on them

**Comment by Danielsio** [comment]
> Collaborator

thing is with the original picture, you get 80% picture and the content get cut off, like you saw previously. 
Maybe if can you get those images with a bit zoom out and still better sharpness it will look good enough.

alternatively, if you can find a way to fix up the scaling part, or get a good slideshow component from a library that's looks good it will be great.

notice the first 3 commits of this pr is the same implementation of the slideshow but from diffrent libraries.

i personally grew tired of this feature since all the implementations i have seen arent something that blew my mind.. compare to other well styled websites

**Pull request closed without merging**
