### PR TITLE
Admin dashboard fixes

### LINKED ISSUE #57: Fix UI in admin dashboard - bigger buttons
The current three buttons are small. I suggest three big horizontal squares.

### LINKED ISSUE #75: No "course ID" in the courseItem and in "edit course"
There is no "course ID" field in the `courseItem` component which is displayed on `AdminCoursesDashboard`.
Also, you cannot change the "course ID" from the "edit course" page. Is it a bug or a feature?

### PR DESCRIPTION
**Pull request by itayf9**
I've made some changes in the admin dashboard UI and I've made some other minor changes throughout the app as well.

- Redesigned the admin dashboard main page.
Old: 
צילום מסך 2023-07-31 171224

New:
צילום מסך 2023-08-05 161418

- Added new header for each of the paged throughout the app.
- Created more subcomponents from existing code (such as `PageHeader.jsx`, `DeleteCoursesConfirmationModal.jsx`, `ShowMoreLessButton.jsx`, `SubjectsViewer.jsx`).
- Reorganized the /components directory to include subdirectories.
- Redesigned the course item component.
New:
צילום מסך 2023-08-05 145141

- Added the course id field to the course item component and to the edit form (read only - you cannot change the course id).
- Added the course id and name to the deletion modal.
New:
צילום מסך 2023-08-05 150549

- Fixed some layout to "cancel" and "save" buttons throughout the app.
- Removed some code duplications.

closes #57 
closes #75

### CODE REVIEW

**Review by Danielsio — APPROVED** [review]
Well Done Itay, your changes are far better then i expected.

Keep up the good work !!

**Comment by Danielsio** [comment]
could you please include the fix in line 492:
`<GoogleCalendarButton handleOpenCalendar={{handleOpenCalendar}}/>` => 
`<GoogleCalendarButton handleOpenCalendar={handleOpenCalendar}/>`

**Review by oshriFadlon1 — APPROVED** [review]
look very good itay.

**Comment by itayf9** [comment]
> could you please include the fix in line 492: <GoogleCalendarButton handleOpenCalendar=`{{handleOpenCalendar}}/>` => <GoogleCalendarButton handleOpenCalendar=`{handleOpenCalendar}/>`

fixed

**Pull request merged**
